enable-debug-messages: true
vote-data:
  reward-same-ips: false
  notify-urls: []
  password: ""
  currency-name: "currency"
  base-currency-given: 10.0
  whole-currency-only: true
  rewards: {}
  queued-rewards: {}
  broadcast: "&6{PLAYER} &avoted and received &6{REWARD}&a!"
  allowed-services: []
  vote-description: "&6Vote at these sites to earn rewards!"
  vote-sites: {}
  vote-promotions-world: "world"
  vote-promotions:
    neon-rank:
      votes: 6
      rank: "Neon"
      remove-ranks:
      - "Initiate"
      message: "&bYou've voted enough for a promotion to &6Neon&b, congrats!"
    steel-rank:
      votes: 14
      rank: "Steel"
      remove-ranks:
      - "Initiate"
      - "Neon"
      message: "&bYou've voted enough for a promotion to &7Steel&b, congrats!"
json-data:
  testing-mode: false
  notice-enabled: false
  notice-message: ""
database:
  hostname: "localhost:3306"
  username: "databaseuser"
  password: "databasepass"
  database: "databasename"
auth-levels:
  owner: 0
  founder: 1
  admin: 1
  moderator: 2
  carbon: 128
  platinum: 129
  steel: 130
  neon: 131
  vip: 132
  initiate: 254
discord:
  bot-token: ""
  cleverbot-api-key: ""
  use-cleverbot: true
  rank-syncing: false
  console-id: ""
  emojis:
    coin-flip-front: "fcoin"
    coin-flip-back: "bcoin"
    ping-emoji: "ping_pong"
  commands:
    ip: "Minecraft IP: **team-carbon.net**"
    site: "Team-Carbon Website: **http://team-carbon.net/**"
    votes: "You've voted for the server {VOTE_COUNT} times!"
  ranks:
    server-rank: "discord-rank"
