name: ${artifactId}
author: OffLuffy
description: Web utilties for Team-Carbon
version: ${version}
main: net.teamcarbon.carbonweb.CarbonWeb
depends: [Vault, Votifier]
softdepend: [Essentials]
commands:
  carbonwebtest:
    description: A debugging command to test various things
    usage: /cwtest [vote|count]
    aliases: [cwtest, webtest, cwt]
    permission: carbonweb.debug
  carbonwebreload:
    description: Reloads config values
    usage: /cwreload
    aliases: [cwreload, webreload, cwr]
    permission: carbonweb.reload
  carbonwebnotice:
    description: Set or toggle the JSON notice
    usage: /cwnotice [on|off|set <msg>|test <on|off>]
    aliases: [cwnotice, webnotice, notice]
    permission: carbonweb.notice
  carbonwebvote:
    description: Vote command
    usage: /vote
    aliases: [cwvote, webvote, cwv, votes, vote]
  carbonweblink:
    description: Link your minecraft account to the website
    usage: /link
    aliases: [cwlink, weblink, cwl, link]
  carbonwebreward:
    description: Manage vote rewards
    usage: /reward [addtier|additem|remtier|remitem|edittier|edititem|givereward]
    aliases: [cwreward, webreward, cwrw, reward]
  carbonwebcleverbot:
    description: Talk with CleverBot
    usage: /cbot <phrase>
    aliases: [cwcleverbot, webcleverbot, cwcb, cleverbot, cb, cbot]
permission:
  carbonweb.reload:
    description: Allows reloading CarbonWeb's config
    default: op
  carbonweb.notice:
    description: Allows setting and toggling the JSON notice
    default: op
  carbonweb.vote:
    description: Use the vote command to list sites and see vote count
    default: true
  carbonweb.cleverbot:
    description: Allows using a command to have a private conversation with CleverBot
    default: op
  carbonweb.cleverbot.broadcast:
    description: Allows using @CleverBot in a message to have a public conversation with CleverBot
    default: op